### ISSUE TITLE
Unable to start using Approved Users

### ISSUE THREAD

**Issue by colindmiller** [GilesMetcalf/approved_users#2]
Hi Giles

I am tearing my hair out here (what little there is of it).  I've followed your instructions and uploaded the Approved Users plugin to my site as I need the user management functions it offers.  I've signed in as Admin and ticked the box, refreshed the page, logged out and logged back in, left it a day, left it a week.  The tab does not appear.  What am I doing wrong and what do I need to do to fix this?

I am using Wolf CMS **0.8.3.1**

Cheers
Colin D Miller

**Attached:** screenshot of my admin area ...
![whereisthetab](https://cloud.githubusercontent.com/assets/15924499/11269686/688b8128-8eb0-11e5-903d-9aadfdebb7ea.png)

**Comment by GilesMetcalf** [comment]
Hi Colin,
If you are getting the same issue with Martin's "Registered Users" code then the problem lies deeper in the code than I have been wading. As you can see, my plugin is a fork of Martin's. However, I will try to help. If you are not seeing anything in the server logs (I think that Wolf tries to hide a lot of that away) try turning on the Wolf debug mode. Open the Wolf config.php file in a text editor, find the "DEBUG" entry, and set it to true. Then, when something goes "Kerblooey!", there should be a red banner with the error in it. Usually...

**Comment by colindmiller** [comment]
Hi Giles

So frustrating!  Looked at the server error logs (which is shared by all 
websites) but there was nothing for my IP address on the JustHost 
service.  I then turned DEBUG on and found all the plug-in information 
disappeared.  And still nothing appeared in the error logs.  Has this 
anything to do with the new version of Wolf, or is it working okay on 
your sites?  What else do you suggest?

Cheers
_Colin_

---

Phone: _07810 334667_
e-mail: _me@colindmiller.com_

---

**Comment by colindmiller** [comment]
Got it working Giles.  I'll have fun now ...

Cheers
_Colin_

**Comment by GilesMetcalf** [comment]
Glad you got it working, Colin. What was the issue?

**Comment by colindmiller** [comment]
Hi Giles

When I downloaded the plugin from GitHub I left the full folder name as
"approved_users-master" - which is what I uploaded to the website.  I also
set the ".htm" flag to false as this can mess things up.  But I think it
was the renaming of the folder to "approved_users" that did the trick. 
Created a really smooth login/logout experience, so I am best pleased with
the plugin.

Thank you for your responsive and thoughtful support.

Cheers
Colin

## Original email:

**Comment by GilesMetcalf** [comment]
Ah, it's always the simple things! Pleased you got it working. If your happy with this, I will close this issue now?

**Comment by colindmiller** [comment]
More than happy for this to be closed.

Many thanks
_Colin_

---

Phone: _07810 334667_
e-mail: _me@colindmiller.com_

---
